packages:
  - packages/*
  - website

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - "@hamk-uas/jax-js-nonconsuming"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - msw
  - protobufjs
